POST http://localhost:8000/api/user
Content-Type: application/json

{
    "password" : "123456",
    "fullname" : "Xuân Ý",
    "email" : "xuany@gmail.com",
    "age": 22,
    "avatar" : "https://i.pinimg.com/564x/5e/21/b5/5e21b5fa45cc04f8fd35537496ebe6d0.jpg"
}
###

POST http://localhost:8000/api/user/signin
Content-Type: application/json

{
    "password" : "123456",
    "email" : "huynh@gmail.com"
}

###

POST http://localhost:8000/api/user/signin
Content-Type: application/json

{
    "password" : "123456",
    "email" : "xuany@gmail.com"
}

###

POST http://localhost:8000/api/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjc3MzMwMDYzLCJleHAiOjE2Nzc0MTY0NjN9.fn9et6FwWxpq7cR9cbLVyKKhVuJczE3CvR9VZIgormg
Content-Type: application/json
