POST http://localhost:8000/api/user
Content-Type: application/json

{
    "password" : "123456",
    "fullname" : "Luu Huynh",
    "email" : "lhuynh@gmail.com",
    "age": 17
}
###

POST http://localhost:8000/api/user/signin
Content-Type: application/json

{
    "password" : "123456",
    "email" : "huynh@gmail.com"
}

###

POST http://localhost:8000/api/user/signin
Content-Type: application/json

{
    "password" : "123456",
    "email" : "xuany@gmail.com"
}

###

POST http://localhost:8000/api/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjc3MzMwMDYzLCJleHAiOjE2Nzc0MTY0NjN9.fn9et6FwWxpq7cR9cbLVyKKhVuJczE3CvR9VZIgormg
Content-Type: application/json
